spring.application.name=Config

server.port=4010

# Config server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./config-repo
# spring.cloud.config.server.bootstrap=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:4015/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.log-delta-diff=false
