server.port=4020

# Gateway config for development
spring.cloud.loadbalancer.cache.enabled=false
eureka.client.registry-fetch-interval-seconds=10

# Routes common config
spring.cloud.gateway.server.webmvc.default-filters[0]=RemoveRequestHeader=X-Internal-Request
spring.cloud.gateway.server.webmvc.default-filters[1]=RemoveRequestHeader=X-Account-Id
spring.cloud.gateway.server.webmvc.default-filters[2]=RemoveRequestHeader=X-Account-Role
spring.cloud.gateway.server.webmvc.default-filters[3]=AddRequestHeader=X-Internal-Request, false

# Routes
spring.cloud.gateway.server.webmvc.routes[0].id=vehicle-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://VehicleService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/vehicles/**

spring.cloud.gateway.server.webmvc.routes[1].id=parkingLot-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ParkingLotService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/parkingLots/**

spring.cloud.gateway.server.webmvc.routes[2].id=reservation-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ReservationService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/reservations/**

spring.cloud.gateway.server.webmvc.routes[3].id=payment-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://PaymentService
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/payments/**, /api/v1/payouts/**

spring.cloud.gateway.server.webmvc.routes[4].id=user-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://UserService
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/auth/**, /api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[5].id=storage-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://StorageService
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/storage/**

# Security
security.jwt.publicKey=MIIBI...

security.exclude.routes[0]=/api/v1/auth/register
security.exclude.routes[1]=/api/v1/auth/verify
security.exclude.routes[2]=/api/v1/auth/login
security.exclude.routes[3]=/api/v1/auth/refresh
security.exclude.routes[4]=/api/v1/auth/forgot-password
security.exclude.routes[5]=/api/v1/auth/reset-password
