server.port=4005

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3310/NotificationService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

# RabbitMQ
spring.rabbitmq.host=100.64.0.1
spring.rabbitmq.port=3311
spring.rabbitmq.username=parknexus
spring.rabbitmq.password=12345678

rabbitmq.exchange.notification=notification.exchange

rabbitmq.queue.notification.registration=email.registration.queue
rabbitmq.queue.notification.passwordReset=email.passwordReset.queue
rabbitmq.queue.notification.autoCheckOut=email.autoCheckOut.queue

rabbitmq.routingKey.notification.registration=notification.email.registration
rabbitmq.routingKey.notification.passwordReset=notification.email.passwordReset
rabbitmq.routingKey.notification.autoCheckOut=notification.email.autoCheckOut


# OneSignal
onesignal.restApiKey=os_v2_app...
onesignal.orgApiKey=os_v2_org...
onesignal.appId=75950d5c...

onesignal.templates.registerOtp=4115a3e0...
onesignal.templates.forgotPasswordOtp=4c83f40a...