server.port=4002

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3303/ReservationService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

# RabbitMQ
spring.rabbitmq.host=100.64.0.1
spring.rabbitmq.port=3311
spring.rabbitmq.username=parknexus
spring.rabbitmq.password=12345678

rabbitmq.exchange.notification=notification.exchange
rabbitmq.exchange.reservation=reservation.exchange

rabbitmq.queue.reservation.autoCheckOut=reservation.autoCheckOut.queue
rabbitmq.queue.reservation.autoCancel=reservation.autoCancel.queue

rabbitmq.routingKey.notification.autoCheckOut=notification.email.autoCheckOut
rabbitmq.routingKey.notification.autoCancel=notification.email.autoCancel

rabbitmq.routingKey.reservation.autoCheckOut=reservation.autoCheckOut
rabbitmq.routingKey.reservation.autoCancel=reservation.autoCancel



