server.port=4006

# Multipart File Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# GCP Storage & Credentials
spring.cloud.gcp.storage.bucket=parknexus-api
spring.cloud.gcp.credentials.location=classpath:gc-service-acc.json