spring.application.name=ParkingLotService

server.port=4001

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3302/ParkingLotService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:4010/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true