services:
  database:
    image: mysql/mysql-server:8.0.25
    container_name: vti-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
