server.port=8762

# DepartmentService
spring.cloud.gateway.server.webmvc.routes[0].id=department-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://DepartmentService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/departments/**

# PositionService
spring.cloud.gateway.server.webmvc.routes[1].id=position-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PositionService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/positions/**

# AccountService
spring.cloud.gateway.server.webmvc.routes[2].id=account-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://AccountService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/accounts/**