spring.application.name=PositionService

server.port=4001

spring.dataSource.url=jdbc:mysql://localhost:3307/TestingSystem?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG