spring.application.name=UserService

server.port=4004

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3305/UserService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=100.64.0.1
spring.data.redis.port=3306
spring.data.redis.password=12345678

# Eureka
eureka.client.service-url.defaultZone=http://localhost:4010/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
