spring.application.name=ReservationService

server.port=4002

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3303/ReservationService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true