# Global configs ---------------------------------------------------

# Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Eureka 
eureka.client.service-url.defaultZone=http://localhost:4015/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG