server.port=4004

# Database
spring.dataSource.url=jdbc:mysql://100.64.0.1:3305/UserService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

# Redis
spring.data.redis.host=100.64.0.1
spring.data.redis.port=3306
spring.data.redis.password=12345678

# OneSignal
onesignal.rest-api-key=os_v2_app_owkq2xgszzbwlbkjtvwuyfre52ddmkpuvv7em246ifidwqlsqpec5sbt74big3phazibxb4cknum3eud7earcxyqw4pxgpusu6cswqa
onesignal.org-api-key=os_v2_org_fjogedrqibe7djo24lddc5hkj3foo7s7adcerk4hajhfmdkoxgumfaft2biutum6yylwpdoagqxlmt2vu62efmrzwtkzpxcqroydkei
onesignal.app-id=75950d5c-d2ce-4365-8549-9d6d4c1624ee
