server.port=4000

spring.dataSource.url=jdbc:mysql://100.64.0.1:3301/VehicleService?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678