spring.application.name=ApiGateway

server.port=4020

# Eureka
eureka.client.service-url.defaultZone=http://localhost:4010/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true