services:
  database:
    image: mysql/mysql-server:8.0.25
    container_name: ParkNexus-VehicleService-DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3301:3306"
